DELETE FROM telefone;
DELETE FROM endereco;
DELETE FROM pessoa;

ALTER TABLE telefone ALTER COLUMN codigo RESTART WITH 1;
ALTER TABLE endereco ALTER COLUMN codigo RESTART WITH 1;
ALTER TABLE pessoa ALTER COLUMN codigo RESTART WITH 1;
